### PR TITLE
Fix Travis testing and solium warnings

### PR DESCRIPTION
**Pull request by sorpaas**
* Fixed all current Solium compiler warnings. One particular change is `Owned::only_owner` to `Owned::onlyOwner`, because it seems that it should be camel case.
* Added a simple `TestOwned` test, otherwise test coverage cannot be generated and it causes Travis to fail.
* Update solidity-coverage to 0.5.0 to reduce the amount of test warnings.

### CODE REVIEW

**Comment by svyatonik** [comment]
I do not have a strong opinion on what to do with this PR :) Right now I'd prefer to postpone it, but merge at will :)

Here are my thoughts:
1) this won't 'unlock' #1 (and dependent #2), because the problem is [unrelated](https://github.com/parity-contracts/secretstore-service/pull/1#issuecomment-384255189)
2) #1 has already solved the coverage issue by adding tests for service contract
3) test added here should be removed when merged with #1, because it is redundant (coverage is at 100% there && imho it is better to test methods in the context of final contracts of the repo (here: service contracts), not the base ones)
4) both adding `emit` and changing `only_owner` to `onlyOwner` are changing the contract bytecode => merging this will invalidate data from #2 (=> contracts redeploy is required). It wasn't there initially, because:
4.1) when first versions of service contracts have been developed, there were no `emit` keyword
4.2) when first versions of service contracts have been developed, they were residing in old `contracts` repo with `only_owner` modifier. I haven't changed anything when copied files from that repo.

**Comment by svyatonik** [comment]
@sorpaas Hey, since PR #1 has been approved recently and given that our requirements to the `master` branch have been softened (see https://github.com/parity-contracts/secretstore-key-server-set/pull/4#issuecomment-396215987 ), let's merge this, but could you please remove `testSetOwner` before? It is redundant now.

**Comment by sorpaas** [comment]
@svyatonik Fixed! I also updated it to align with our current templates, and fixed warnings compiling against newer version of Solidity.

**Comment by sorpaas** [comment]
@svyatonik I think it's an implicit requirement right now. I only found in the spec about requirements to include ABI, but it indeed doesn't mention which way. But our template (https://github.com/parity-contracts/template/blob/master/template.toml#L2) has the `abis` folder, and it's present in most of our `parity-contracts` repo. So I think it'd be better to have it. :)

Ping @kirushik.

**Comment by svyatonik** [comment]
okay, let's have it :) will need to change a #2

**Pull request merged**
