### PR TITLE
Initial contracts version

### PR DESCRIPTION
**Pull request by svyatonik**
Description: https://github.com/paritytech/parity/pull/8029

### CODE REVIEW

**Comment by folsen** [comment]
Sorry for the trouble moving stuff around.

**Comment by folsen** [comment]
@svyatonik ping me when it's ready to review and merge, I'll do my best to review

**Comment by svyatonik** [comment]
@folsen Thanks! Sure :)

**Comment by svyatonik** [comment]
To anyone who's going to review this, here are my responses for errors on `Buildkite`:
- `Unused state variables in contracts, Contract: *XXX*, Vars set([u'keyServerSetAddress'])` - I don't get why it is marked as unused, because it is [actually used](https://github.com/parity-contracts/secretstore-service/blob/ff001ecf26d438dd7f1fa665b8c754e9d94ee504/contracts/SecretStoreServiceBase.sol#L67) in contracts base class (see `SecretStoreServiceBase.sol`);
- `Deletion on struct with mapping in contracts, Contract: SecretStoreDocumentKeyShadowRetrievalService, Func/Struct: [(u'clearDocumentKeyShadowRetrievalRequest', u'DocumentKeyShadowRetrievalRequest')]` - nested mapping is cleared couple of lines [above](https://github.com/parity-contracts/secretstore-service/blob/ff001ecf26d438dd7f1fa665b8c754e9d94ee504/contracts/SecretStoreDocumentKeyShadowRetrievalService.sol#L329).

Please check if my assumptions are correct when reviewing.

**Comment by sorpaas** [comment]
Haven't figured out which part of the analyzer caused `unused state variables`, but the second one `deletion on struct with mapping in contracts` is definitely a false positive.

The analyzer looks like simply fetch all `delete` commands, and then check the type signature. If the type signature contains a `mapping` inside, then it will throw out the error. 

From our code mappings are indeed cleared out.

**Pull request merged**
